spring:
  datasource:
    url:
    username:
    password:
    driver-class-name:
  servlet:
    multipart:
      maxFileSize:
      maxRequestSize:
  security:
    user:
      password:
  jpa:
    open-in-view:
    show-sql:
    hibernate:
      format_sql:
      ddl-auto:

logging:
  level:
    org:
      hibernate:
        SQL:
        type:
          descriptor:
            sql:
              BasicBinder:

cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    s3:
      bucket:
      dir:
    region:
      static:
    stack:
      auto: